name: Deploy Vite site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: cr2007/actions/.github/workflows/gh-pages-deploy.yml@v1
    with:
      build-command: GITHUB_PAGES=true GITHUB_REPO=${{ github.event.repository.name }} nr build
      output-dir: dist
